
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtgSexo = new javax.swing.ButtonGroup();
        CbxUf = new javax.swing.JPanel();
        LblNome = new javax.swing.JLabel();
        JtfNome = new javax.swing.JTextField();
        LblTelefone = new javax.swing.JLabel();
        JtfTelefone = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        JtfEmail = new javax.swing.JTextField();
        CbxUF = new javax.swing.JComboBox<>();
        LblUf = new javax.swing.JLabel();
        RdbFeminino = new javax.swing.JRadioButton();
        RdbMasculino = new javax.swing.JRadioButton();
        LblSexo = new javax.swing.JLabel();
        CkbMenor = new javax.swing.JCheckBox();
        BtgLimpar = new javax.swing.JButton();
        BtgGravar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtgRemover = new javax.swing.JButton();
        BtgFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblNome.setText("Nome");

        JtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfNomeActionPerformed(evt);
            }
        });

        LblTelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblTelefone.setText("Telefone");

        LblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblEmail.setText("E-mail");

        CbxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RR", "RO", "RJ", "RN", "RS", "SC", "SP", "SE", "TO" }));
        CbxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxUFActionPerformed(evt);
            }
        });

        LblUf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblUf.setText("UF");

        BtgSexo.add(RdbFeminino);
        RdbFeminino.setText("Feminino");

        BtgSexo.add(RdbMasculino);
        RdbMasculino.setText("Masculino");

        LblSexo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblSexo.setText("SEXO");

        CkbMenor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CkbMenor.setText("Menor de idade");

        BtgLimpar.setText("Limpar");
        BtgLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtgLimparActionPerformed(evt);
            }
        });

        BtgGravar.setText("Gravar");
        BtgGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtgGravarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone", "E-mail", "UF", "Sexo", "Menor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtgRemover.setText("Remover");
        BtgRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtgRemoverActionPerformed(evt);
            }
        });

        BtgFechar.setText("Fechar");
        BtgFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtgFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CbxUfLayout = new javax.swing.GroupLayout(CbxUf);
        CbxUf.setLayout(CbxUfLayout);
        CbxUfLayout.setHorizontalGroup(
            CbxUfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CbxUfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CbxUfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CbxUfLayout.createSequentialGroup()
                        .addComponent(LblTelefone)
                        .addGap(3, 3, 3)
                        .addComponent(JtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CbxUfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CbxUfLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtgLimpar)
                                .addGap(163, 163, 163))
                            .addGroup(CbxUfLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LblEmail)
                                .addGap(18, 18, 18)
                                .addComponent(JtfEmail))))
                    .addGroup(CbxUfLayout.createSequentialGroup()
                        .addComponent(LblNome)
                        .addGap(18, 18, 18)
                        .addComponent(JtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CbxUfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BtgGravar)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CbxUfLayout.createSequentialGroup()
                            .addComponent(BtgRemover)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtgFechar))))
                .addGap(17, 17, 17))
            .addGroup(CbxUfLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(LblUf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(LblSexo)
                .addGap(18, 18, 18)
                .addComponent(RdbFeminino)
                .addGap(18, 18, 18)
                .addComponent(RdbMasculino)
                .addGap(45, 45, 45)
                .addComponent(CkbMenor)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CbxUfLayout.setVerticalGroup(
            CbxUfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CbxUfLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(CbxUfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNome)
                    .addComponent(JtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(CbxUfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTelefone)
                    .addComponent(JtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblEmail)
                    .addComponent(JtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(CbxUfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblUf)
                    .addComponent(LblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdbFeminino)
                    .addComponent(RdbMasculino)
                    .addComponent(CkbMenor))
                .addGap(30, 30, 30)
                .addGroup(CbxUfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtgLimpar)
                    .addComponent(BtgGravar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(CbxUfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtgRemover)
                    .addComponent(BtgFechar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CbxUf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CbxUf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtgLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtgLimparActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Deseja limpar os dados?",
                "Confirmação",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            
            JtfNome.setText("");
            JtfTelefone.setText("");
            JtfEmail.setText("");
            CbxUF.setSelectedItem("AC");
            BtgSexo.clearSelection();
            CkbMenor.setSelected(false);
        }
    }//GEN-LAST:event_BtgLimparActionPerformed

    private void BtgGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtgGravarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        String linha[]=new String[6];
        linha[0]=JtfNome.getText();
        linha[1]=JtfTelefone.getText();
        linha[2]=JtfEmail.getText();
        linha[3]=CbxUF.getSelectedItem().toString();
        linha[4]=(RdbFeminino.isSelected())?"Feminino":"Masculino";
        linha[5]=CkbMenor.isSelected()?"Sim":"Não";
        
        modelo.addRow(linha);
        JtfNome.setText("");
        JtfTelefone.setText("");
        JtfEmail.setText("");
        CbxUF.setSelectedItem("AC");
        BtgSexo.clearSelection();
        CkbMenor.setSelected(false);
        JtfNome.requestFocus();        
    }//GEN-LAST:event_BtgGravarActionPerformed

    private void JtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfNomeActionPerformed

    private void CbxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxUFActionPerformed

    private void BtgRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtgRemoverActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        
        if(jTable1.getSelectedRow() >= 0){
        
            modelo.removeRow(jTable1.getSelectedRow());
            jTable1.setModel(modelo);
            
        }else{
        
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        
        }
        
        
    }//GEN-LAST:event_BtgRemoverActionPerformed

    private void BtgFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtgFecharActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Deseja sair", "Confirmação",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        
        if(response == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_BtgFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtgFechar;
    private javax.swing.JButton BtgGravar;
    private javax.swing.JButton BtgLimpar;
    private javax.swing.JButton BtgRemover;
    private javax.swing.ButtonGroup BtgSexo;
    private javax.swing.JComboBox<String> CbxUF;
    private javax.swing.JPanel CbxUf;
    private javax.swing.JCheckBox CkbMenor;
    private javax.swing.JTextField JtfEmail;
    private javax.swing.JTextField JtfNome;
    private javax.swing.JTextField JtfTelefone;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblSexo;
    private javax.swing.JLabel LblTelefone;
    private javax.swing.JLabel LblUf;
    private javax.swing.JRadioButton RdbFeminino;
    private javax.swing.JRadioButton RdbMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
